name: Deploy Nginx

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install the gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Build and push the Docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}  # Define environment variable here
        run: |  # Multi-line commands with proper indentation
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/travel-europe-llc-main/$GOOGLE_PROJECT/nginx:latest .
          docker push us-central1-docker.pkg.dev/travel-europe-llc-main/$GOOGLE_PROJECT/nginx:latest